version: '3.8'

services:
  
  mongodb:
    container_name: 'mongodb'
    image: 'mongo:6.0.13'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=rootpassword'
    ports:
      - '27017:27017'
      
  sb-chatrooms:
    container_name: 'chatrooms'
    image: 'rockerle/springbootchatrooms:1.5'
    environment:
      - 'MONGODB_USER=root'
      - 'MONGODB_PASSWORD=rootpassword'
      - 'MONGODB_HOST=mongodb'
    ports:
        - '127.0.0.1:8080:8080/tcp'
    depends_on:
      - mongodb