version: '3.8'

services:
  
  mongodb:
    container_name: 'mongodb'
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=rootpassword'
    ports:
      - '5000:27017'
      
  sb-chatrooms:
    container_name: 'chatrooms'
    image: 'rockerle/springbootchatrooms:latest'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=rootpassword'
    ports:
        - '127.0.0.1:8080:8080/tcp'
    depends_on:
      - mongodb
    links:
      - mongodb