services:
  sb-chatrooms:
    image: 'rockerle/springbootchatrooms:latest'
    ports:
        - 127.0.0.1:8080:8080/tcp
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '5000:27017'
    links:
      - sb-chatrooms
