services:
  
  mongodb:
    container_name: mongodb
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=rootpassword'
    ports:
      - '5000:27017'
      
  sb-chatrooms:
    container_name: chatrooms
    image: 'rockerle/springbootchatrooms:latest'
    ports:
        - 127.0.0.1:8080:8080/tcp
    environment:
        - 'MONGODB_HOST=mongodb'
    depends_on:
        - mongodb