# Github Actions to build and deploy a Spring Bot App
name: 'Build n push'

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: oracle

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_NAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: make graldew executable
        run: chmod +x ./gradlew

      - name: gradlew build
        run: ./gradlew build

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest